-- MySQL Script generated by MySQL Workbench
-- lun. 28 nov. 2016 10:38:22 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DDCSPP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DDCSPP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DDCSPP` DEFAULT CHARACTER SET utf8 ;
USE `DDCSPP` ;

-- -----------------------------------------------------
-- Table `DDCSPP`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`Role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`Theme` (
  `id` INT NOT NULL,
  `color` VARCHAR(6) NULL,
  `img` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `salt` VARCHAR(45) NULL,
  `role_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  PRIMARY KEY (`id`, `role_id`, `theme_id`),
  INDEX `fk_User_role1_idx` (`role_id` ASC),
  INDEX `fk_User_theme1_idx` (`theme_id` ASC),
  CONSTRAINT `fk_User_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `DDCSPP`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_theme1`
    FOREIGN KEY (`theme_id`)
    REFERENCES `DDCSPP`.`Theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DDCSPP`.`Bloc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DDCSPP`.`Bloc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(70) NULL,
  `describe` VARCHAR(500) NULL,
  `img` VARCHAR(250) NULL,
  `audio` VARCHAR(250) NULL,
  `video` VARCHAR(250) NULL,
  `format` VARCHAR(10) NULL,
  `date` DATE NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`),
  INDEX `fk_post_User_idx` (`User_id` ASC),
  CONSTRAINT `fk_post_User`
    FOREIGN KEY (`User_id`)
    REFERENCES `DDCSPP`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
